import { test, expect, type Page } from '@playwright/test'
import { ArticleEditorPage, capturedEmails, closeDb, createAccount, db, removeMyAccounts, signedIn, uniqueTitle } from './helpers/workflow'

// Two browsers use different accounts. SQL only prepares accounts and reads back
// state; every profile mutation below uses its actual control.
test.afterAll(async () => { await removeMyAccounts(); await closeDb() })
async function saved(page: Page, path: string, act: () => Promise<unknown>) {
  const waiting = page.waitForResponse(r => new URL(r.url()).pathname === path && r.request().method() === 'PATCH')
  await act()
  expect((await waiting).status()).toBe(200)
}

test('legacy administrator profile edits, cancels, retries, restores biography and preserves private notes', async ({ browser }) => {
  test.setTimeout(150_000) // Independent fields, permission changes and fresh-page persistence; each action retains 10/15s deadlines.
  const account = await createAccount('WRITER', 'legacy-profile')
  const ctx = await signedIn(browser, 'admin')
  const page = await ctx.newPage()
  const path = `/api/editorial/users/${account.id}`
  await page.goto(`/editorial/users/${account.id}`, { waitUntil: 'networkidle' })
  await new ArticleEditorPage(page).dismissCookieBanner()
  await page.getByRole('button', { name: 'Edit Full Name', exact: true }).click()
  await page.getByLabel('Full Name', { exact: true }).fill('Cancelled name')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect((await db().user.findUniqueOrThrow({ where: { id: account.id } })).name).not.toBe('Cancelled name')
  const name = uniqueTitle('Profile name')
  await page.getByRole('button', { name: 'Edit Full Name', exact: true }).click()
  await page.getByLabel('Full Name', { exact: true }).fill(name)
  await page.route(`**${path}`, r => r.request().method() === 'PATCH' ? r.fulfill({ status: 503, json: { error: 'Profile service unavailable' } }) : r.continue())
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Profile service unavailable' })).toBeVisible()
  await expect(page.getByLabel('Full Name', { exact: true })).toHaveValue(name)
  await page.unroute(`**${path}`)
  await saved(page, path, () => page.getByRole('button', { name: 'Save', exact: true }).click())
  for (const [label, value] of [['Author Page Slug', `profile-${account.id}`], ['Photo URL', '/logo.png']] as const) {
    await page.getByRole('button', { name: `Edit ${label}`, exact: true }).click()
    await page.getByLabel(label, { exact: true }).fill(value)
    await saved(page, path, () => page.getByRole('button', { name: 'Save', exact: true }).click())
  }
  for (const biography of ['A changed author biography.', '']) {
    await page.getByLabel('Biography').fill(biography)
    await saved(page, path, () => page.getByLabel('Biography').blur())
    expect((await db().user.findUniqueOrThrow({ where: { id: account.id } })).bio ?? '').toBe(biography)
  }
  await page.getByLabel('Role', { exact: true }).selectOption('EDITOR')
  await page.getByRole('alertdialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  expect((await db().user.findUniqueOrThrow({ where: { id: account.id } })).role).toBe('WRITER')
  await page.getByLabel('Role', { exact: true }).selectOption('EDITOR')
  await saved(page, path, () => page.getByRole('alertdialog').getByRole('button', { name: 'Change to EDITOR' }).click())
  const category = await db().category.findFirstOrThrow()
  await page.getByRole('checkbox', { name: category.name, exact: true }).check()
  await saved(page, path, () => page.getByRole('button', { name: 'Save categories' }).click())
  expect(await db().categoryEditor.count({ where: { userId: account.id, categoryId: category.id } })).toBe(1)
  const notes = page.getByPlaceholder('Private notes about this account (e.g. availability, communication preferences, issues)…')
  const privateNote = uniqueTitle('Private administrator note')
  await notes.fill(privateNote)
  await page.route(`**${path}`, r => r.request().method() === 'PATCH' ? r.abort('failed') : r.continue())
  await page.getByRole('button', { name: 'Save Notes' }).click()
  await expect(page.getByRole('alert').filter({ hasText: /network|fetch|connect/i })).toBeVisible()
  await expect(notes).toHaveValue(privateNote)
  await expect(page.getByRole('button', { name: 'Save Notes' })).toBeEnabled()
  await page.unroute(`**${path}`)
  await saved(page, path, () => page.getByRole('button', { name: 'Save Notes' }).click())
  await page.getByRole('button', { name: 'Set Password Directly' }).click()
  await page.getByLabel('New password', { exact: true }).fill('short')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Password must be at least 8 characters.' })).toBeVisible()
  await expect(page.getByLabel('New password', { exact: true })).toHaveValue('short')
  await page.getByLabel('New password', { exact: true }).fill('Controlled-profile-password-123')
  await saved(page, path, () => page.getByRole('button', { name: 'Save', exact: true }).click())
  const before = capturedEmails().filter(m => m.to === account.email).length
  const reset = page.waitForResponse(r => new URL(r.url()).pathname === '/api/editorial/password-reset' && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Send Password Reset Email' }).click()
  expect((await reset).status()).toBe(200)
  await expect.poll(() => capturedEmails().filter(m => m.to === account.email).length).toBeGreaterThan(before)
  await saved(page, path, () => page.getByRole('button', { name: 'Deactivate Account' }).click())
  expect((await db().user.findUniqueOrThrow({ where: { id: account.id } })).isActive).toBe(false)
  await saved(page, path, () => page.getByRole('button', { name: 'Reactivate Account' }).click())
  await page.reload({ waitUntil: 'networkidle' })
  await expect(notes).toHaveValue(privateNote)
  await expect(page.getByLabel('Biography')).toHaveValue('')
  await expect(page.getByLabel('Role', { exact: true })).toHaveValue('EDITOR')
  await expect(page.getByRole('checkbox', { name: category.name, exact: true })).toBeChecked()
  const editor = await signedIn(browser, 'editor')
  expect((await editor.request.get(path)).status()).toBe(403)
  const denied = await editor.newPage()
  await denied.goto(`/editorial/users/${account.id}`, { waitUntil: 'networkidle' })
  await expect(denied.getByText(privateNote, { exact: true })).toHaveCount(0)
  await expect(denied).not.toHaveTitle(new RegExp(name))
  await editor.close()
  await ctx.close()
})

test('administrator warnings, private notes, detail load recovery and audit log failures use visible retry controls', async ({ browser }) => {
  test.setTimeout(120_000)
  const account = await createAccount('READER', 'warning-panel')
  const ctx = await signedIn(browser, 'admin')
  const page = await ctx.newPage()
  await page.goto('/editorial/users', { waitUntil: 'networkidle' })
  await new ArticleEditorPage(page).dismissCookieBanner()
  await page.getByPlaceholder('Search name or email...').fill(account.email)
  await expect(page.getByText('Showing 1 to 1 of 1 users')).toBeVisible()
  const detail = `/api/admin/users/${account.id}`
  await page.route(`**${detail}`, r => r.fulfill({ status: 503, json: { error: 'User details unavailable' } }))
  await page.locator('tr', { hasText: account.email }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'User details unavailable' })).toBeVisible()
  await page.unroute(`**${detail}`)
  const loaded = page.waitForResponse(r => new URL(r.url()).pathname === detail)
  await page.getByRole('button', { name: 'Retry user details' }).click()
  expect((await loaded).status()).toBe(200)
  await page.getByRole('button', { name: 'Warn', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Send Warning' })).toBeDisabled()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await db().userWarning.count({ where: { userId: account.id } })).toBe(0)
  await page.getByRole('button', { name: 'Warn', exact: true }).click()
  const reason = uniqueTitle('Controlled warning reason')
  await page.getByPlaceholder('Reason for warning...').fill(reason)
  await page.route(`**${detail}/warn`, r => r.fulfill({ status: 503, json: { error: 'Warning delivery unavailable' } }))
  await page.getByRole('button', { name: 'Send Warning' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Warning delivery unavailable' })).toBeVisible()
  await expect(page.getByPlaceholder('Reason for warning...')).toHaveValue(reason)
  await page.unroute(`**${detail}/warn`)
  const sent = page.waitForResponse(r => new URL(r.url()).pathname === `${detail}/warn`)
  await page.getByRole('button', { name: 'Send Warning' }).click()
  expect((await sent).status()).toBe(200)
  await expect.poll(() => capturedEmails().filter(m => m.to === account.email && m.html.includes(reason)).length).toBe(1)
  await expect(page.getByText(reason, { exact: true })).toBeVisible()
  const note = uniqueTitle('Private panel note')
  await page.getByPlaceholder('Add a private admin note...').fill(note)
  const added = page.waitForResponse(r => new URL(r.url()).pathname === `${detail}/notes` && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Add Note', exact: true }).click()
  expect((await added).status()).toBe(200)
  await expect(page.getByText(note, { exact: true })).toBeVisible()
  for (const tab of ['content', 'activity', 'overview']) await page.getByRole('button', { name: tab, exact: true }).click()
  const stored = await db().adminNote.findFirstOrThrow({ where: { userId: account.id, note } })
  await page.route(`**${detail}/notes/${stored.id}`, r => r.fulfill({ status: 503, json: { error: 'Note deletion unavailable' } }))
  await page.getByLabel('Delete note', { exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Note deletion unavailable' })).toBeVisible()
  await expect(page.getByText(note, { exact: true })).toBeVisible()
  await page.unroute(`**${detail}/notes/${stored.id}`)
  const deleted = page.waitForResponse(r => new URL(r.url()).pathname === `${detail}/notes/${stored.id}` && r.request().method() === 'DELETE')
  await page.getByLabel('Delete note', { exact: true }).click()
  expect((await deleted).status()).toBe(200)
  await expect(page.getByText(note, { exact: true })).toHaveCount(0)
  await page.getByLabel('Close user details', { exact: true }).click()
  await page.route('**/api/admin/audit-log', r => r.fulfill({ status: 503, json: { error: 'Audit service unavailable' } }))
  await page.getByRole('button', { name: 'Audit Log', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Audit service unavailable' })).toBeVisible()
  await page.unroute('**/api/admin/audit-log')
  const audit = page.waitForResponse(r => new URL(r.url()).pathname === '/api/admin/audit-log')
  await page.getByRole('button', { name: 'Retry audit log' }).click()
  expect((await audit).status()).toBe(200)
  await expect(page.getByRole('row').filter({ hasText: account.email }).filter({ hasText: 'Warning issued' }).first()).toBeVisible()
  await ctx.close()
})

test('administrator directory filters, every sort and pagination rank count leaders across pages', async ({ browser }) => {
  test.setTimeout(150_000) // Sixteen isolated accounts plus all filters/sorts; normal per-action deadlines remain unchanged.
  const prefix = `directory-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`
  const users = []
  for (let i = 0; i < 16; i++) users.push(await createAccount('READER', prefix))
  const leader = users[0]
  const article = await db().article.create({ data: { title: uniqueTitle('Directory count'), slug: uniqueTitle('directory-count').toLowerCase().replaceAll(' ', '-'), content: 'Directory count fixture', authorId: leader.id, status: 'DRAFT' } })
  await db().comment.create({ data: { articleId: article.id, userId: leader.id, body: 'Countable directory comment.' } })
  await db().user.update({ where: { id: users[1].id }, data: { isBanned: true } })
  await db().userWarning.create({ data: { userId: users[2].id, reason: 'Controlled filter fixture', issuedBy: 'Isolated test' } })
  const ctx = await signedIn(browser, 'admin')
  const page = await ctx.newPage()
  await page.goto('/editorial/users', { waitUntil: 'networkidle' })
  await new ArticleEditorPage(page).dismissCookieBanner()
  await page.getByPlaceholder('Search name or email...').fill(prefix)
  await expect(page.getByText('Showing 1 to 15 of 16 users')).toBeVisible()
  await page.getByLabel('Next users page').click()
  await expect(page.getByText('Showing 16 to 16 of 16 users')).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('Previous users page').click()
  await page.route('**/api/admin/users?*', r => r.fulfill({ status: 503, json: { error: 'Directory unavailable' } }))
  await page.getByLabel('User sort').selectOption('oldest')
  await expect(page.getByRole('alert').filter({ hasText: 'Directory unavailable' })).toBeVisible()
  await page.unroute('**/api/admin/users?*')
  const retried = page.waitForResponse(r => new URL(r.url()).pathname === '/api/admin/users')
  await page.getByRole('button', { name: 'Retry users' }).click()
  expect((await retried).status()).toBe(200)
  await expect(page.locator('tbody tr').first()).toContainText(leader.email)
  for (const sort of ['articleCount', 'commentCount', 'lastActive', 'createdAt']) {
    const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/admin/users' && new URL(r.url()).searchParams.get('sort') === sort)
    await page.getByLabel('User sort').selectOption(sort)
    expect((await response).status()).toBe(200)
    await expect(page.getByText('Showing 1 to 15 of 16 users')).toBeVisible()
    if (['oldest', 'articleCount', 'commentCount'].includes(sort)) await expect(page.locator('tbody tr').first()).toContainText(leader.email)
  }
  for (const [status, expected] of [['banned', users[1].email], ['warned', users[2].email]] as const) {
    const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/admin/users' && new URL(r.url()).searchParams.get('status') === status)
    await page.getByLabel('User status').selectOption(status)
    expect((await response).status()).toBe(200)
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await expect(page.locator('tbody tr')).toContainText(expected)
  }
  await page.getByLabel('User status').selectOption('active')
  await expect(page.getByText('Showing 1 to 15 of 15 users')).toBeVisible()
  await page.getByLabel('User status').selectOption('')
  for (const role of ['Admin', 'Editor', 'Writer', 'Growth', 'Reader', 'All']) {
    const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/admin/users' && (new URL(r.url()).searchParams.get('role') ?? '') === (role === 'All' ? '' : role.toUpperCase()))
    await page.getByRole('button', { name: role, exact: true }).click()
    expect((await response).status()).toBe(200)
    await expect(page.locator('tbody tr')).toHaveCount(role === 'Reader' || role === 'All' ? 15 : 0)
  }
  await ctx.close()
})
