import {test,expect} from '@playwright/test'
import {ArticleEditorPage,signedIn,uniqueTitle,articleByTitle,removeMyArticles,closeDb,db} from './helpers/workflow'

test.afterAll(async()=>{await removeMyArticles();await closeDb()})

test('refresh and tab closure retain exact unsaved work; recovery requires deliberate Save',async({browser})=>{
 test.setTimeout(90_000) // Includes interrupted save, refresh, closed tab, explicit recovery and fresh reopen.
 const ctx=await signedIn(browser,'writer');let page=await ctx.newPage();let ed=new ArticleEditorPage(page)
 await ed.openNew();const title=uniqueTitle('local-recovery');await ed.title().fill(title);await ed.typeBody('Server text.');const {id}=await ed.saveNow()
 await page.route('**/api/articles/*',async route=>{if(route.request().method()==='PUT')await route.abort('failed');else await route.continue()})
 await ed.title().fill(title+' unsaved');await ed.moveToEnd();await page.keyboard.type(' Exact unsaved punctuation: £4.25 & <local>.')
 await expect.poll(async()=>await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('consilium:draft:')).length)).toBeGreaterThan(0)
 page.on('dialog',d=>void d.accept())
 await page.reload({waitUntil:'networkidle'})
 await expect(page.getByRole('button',{name:'Recover local work'})).toBeVisible()
 await expect(ed.body()).toHaveText('Server text.')
 await page.getByRole('button',{name:'Recover local work'}).click()
 await expect(ed.body()).toContainText('Exact unsaved punctuation: £4.25 & <local>.')
 await expect(ed.title()).toHaveValue(title+' unsaved')
 await expect(page.getByRole('status',{name:''}).filter({hasText:'Recovered local work'})).toBeVisible()
 expect((await articleByTitle(title))!.content).not.toContain('Exact unsaved')
 await page.close({runBeforeUnload:false})
 page=await ctx.newPage();ed=new ArticleEditorPage(page);await ed.openExisting(id)
 await page.getByRole('button',{name:'Recover local work'}).click()
 await expect(ed.body()).toContainText('Exact unsaved punctuation: £4.25 & <local>.')
 await ed.saveNow()
 const reopened=await ctx.newPage();await new ArticleEditorPage(reopened).openExisting(id)
 await expect(new ArticleEditorPage(reopened).body()).toContainText('Exact unsaved punctuation: £4.25 & <local>.')
 await expect(reopened.getByRole('button',{name:'Recover local work'})).toHaveCount(0)
 expect((await articleByTitle(title+' unsaved'))!.status).toBe('DRAFT')
 await ctx.close()
})

test('stale recovery refuses silent overwrite and never changes publication status',async({browser})=>{
 const ctx=await signedIn(browser,'writer');const page=await ctx.newPage();const ed=new ArticleEditorPage(page)
 await ed.openNew();const title=uniqueTitle('stale-recovery');await ed.title().fill(title);await ed.typeBody('Initial server text.');const {id}=await ed.saveNow()
 await page.route('**/api/articles/*',async r=>r.request().method()==='PUT'?r.abort('failed'):r.continue())
 await ed.moveToEnd();await page.keyboard.type(' Local stale work.')
 const newer=await ctx.newPage();const second=new ArticleEditorPage(newer);await second.openExisting(id);await second.moveToEnd();await newer.keyboard.type(' New server content.');await second.saveNow()
 page.on('dialog',d=>void d.accept());await page.unrouteAll();await page.reload({waitUntil:'networkidle'})
 await expect(page.getByText('The server has changed since this copy.',{exact:false})).toBeVisible()
 await page.getByRole('button',{name:'Recover local work'}).click()
 expect((await ed.saving(()=>ed.saveDraftButton().click())).status()).toBe(409)
 await expect(page.getByRole('button',{name:'Keep my version'})).toBeVisible()
 expect((await articleByTitle(title))!.content).toContain('New server content.')
 expect((await articleByTitle(title))!.status).toBe('DRAFT')
 await page.getByRole('button',{name:'Discard mine and reload'}).click()
 await expect(ed.body()).toContainText('New server content.')
 await expect(ed.body()).not.toContainText('Local stale work.')
 await ctx.close()
})

test('another signed-in account cannot recover a writer draft stored on the same device',async({browser})=>{
 const ctx=await signedIn(browser,'writer');const page=await ctx.newPage();const ed=new ArticleEditorPage(page)
 await ed.openNew();const title=uniqueTitle('owned-recovery');await ed.title().fill(title);await ed.typeBody('Saved.');const{id}=await ed.saveNow()
 await page.route('**/api/articles/*',async r=>r.request().method()==='PUT'?r.abort('failed'):r.continue());await ed.moveToEnd();await page.keyboard.type(' Private local work.')
 const row=await db().article.findUniqueOrThrow({where:{id}});expect(row.authorId).toBeTruthy()
 const admin=await signedIn(browser,'admin');await ctx.clearCookies();await ctx.addCookies(await admin.cookies());page.on('dialog',d=>void d.accept());await page.unrouteAll();await page.reload({waitUntil:'networkidle'})
 await expect(page.getByRole('button',{name:'Recover local work'})).toHaveCount(0)
 await expect(ed.body()).not.toContainText('Private local work.')
 await admin.close();await ctx.close()
})
