/**
 * The three admin-overhaul migrations, replayed on a database built from the schema that main had
 * BEFORE this work (tests/fixtures/schema-before-admin-overhaul.sql, generated by Prisma from commit
 * 92eb04b) plus every earlier repository migration, seeded with realistic data:
 * a linked Editor-in-Chief profile, linked and unlinked cards, a debate with its articles and votes.
 *
 * Proves: existing data is preserved byte for byte, nothing about links/uniqueness/foreign keys/RLS
 * regresses, the guard works for a role that cannot see `debates` through RLS, the migrations are
 * idempotent, and the documented rollback restores the previous shape without touching data.
 * Throwaway database per test; nothing outside it is read or written.
 */
import { describe, it, expect } from 'vitest'
import { Client } from 'pg'
import { randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { assertSafeTestDatabaseHost } from '../../scripts/lib/assertSafeTestDatabaseHost'

const base = process.env.TEST_DATABASE_URL!
assertSafeTestDatabaseHost(base, 'TEST_DATABASE_URL')
const sql = (path: string) => readFileSync(path, 'utf8')
const BEFORE = sql('tests/fixtures/schema-before-admin-overhaul.sql')
const EARLIER = [
  '20260408_enable_rls', '20260408_restrict_column_grants', '20260903_enable_rls_remaining_tables', '20261001_team_member_user_link',
  '20261003231314_public_appointments_testing_sessions', '20261005_user_display_titles', '20261006_member_onboarding',
  '20261006153514_discovery_topic_identity', '20261006160355_managed_article_images', '20261006161413_normalized_subscriber_email',
  '20261006161505_article_active_engagement',
].map((f) => sql(`supabase/migrations/${f}.sql`))
const MINE = ['20261010_debate_lifecycle', '20261010_team_member_updated_at', '20261011_hidden_debate_article_guard'].map((f) => sql(`supabase/migrations/${f}.sql`))

const ROLLBACK = `
  DROP TRIGGER IF EXISTS articles_hidden_debate_guard ON articles;
  DROP FUNCTION IF EXISTS prevent_hidden_debate_article_publication();
  ALTER TABLE team_members DROP COLUMN IF EXISTS "updatedAt";
  DROP INDEX IF EXISTS "debates_deletedAt_unpublishedAt_idx";
  ALTER TABLE debates DROP COLUMN IF EXISTS "unpublishedAt", DROP COLUMN IF EXISTS "deletedAt", DROP COLUMN IF EXISTS "deletedById";
`

async function withDatabase(test: (c: Client) => Promise<void>) {
  const admin = new Client({ connectionString: base })
  await admin.connect()
  const name = `consilium_migration_${randomUUID().replaceAll('-', '')}`
  const url = new URL(base)
  url.pathname = `/${name}`
  let client: Client | undefined
  try {
    await admin.query(`CREATE DATABASE "${name}"`)
    client = new Client({ connectionString: url.href })
    await client.connect()
    await client.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon NOLOGIN; END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF; END $$`)
    await client.query(BEFORE)
    for (const file of EARLIER) await client.query(file)
    await test(client)
  } finally {
    await client?.end()
    await admin.query(`DROP DATABASE IF EXISTS "${name}" WITH (FORCE)`)
    await admin.end()
  }
}

async function seed(c: Client) {
  const q = (text: string, values: unknown[] = []) => c.query(text, values)
  await q(`INSERT INTO users(id,email,name,role,"updatedAt") VALUES
    ('u-chief','chief@ed.ac.uk','Chief Person','ADMIN',now()),('u-writer','w@ed.ac.uk','Writer','WRITER',now()),
    ('u-editor','e@ed.ac.uk','Editor','EDITOR',now()),('u-reader','r@ed.ac.uk','Reader','READER',now())`)
  await q(`INSERT INTO team_members(id,"userId",name,role,"publicTier",bio,image,email,"order","isActive") VALUES
    ('c-chief','u-chief','Chief Person','Editor-in-Chief',NULL,'Leads.','/chief.png','chief@ed.ac.uk',1,true),
    ('c-writer','u-writer','Writer','Writer','writer','Writes.',NULL,NULL,50,true),
    ('c-legacy',NULL,'Legacy Member','Senior Editor',NULL,'Old card.',NULL,'legacy@ed.ac.uk',20,true),
    ('c-hidden',NULL,'Hidden Person','Writer',NULL,NULL,NULL,NULL,90,false)`)
  await q(`INSERT INTO articles(id,title,slug,content,"authorId",status,"publishedAt","isDebate","updatedAt") VALUES
    ('a-for','For','a-for','{}','u-writer','PUBLISHED',now(),true,now()),('a-against','Against','a-against','{}','u-writer','PUBLISHED',now(),true,now()),
    ('a-plain','Plain','a-plain','{}','u-writer','PUBLISHED',now(),false,now())`)
  await q(`INSERT INTO debates(id,title,"forArticleId","againstArticleId","isActive","updatedAt") VALUES ('d1','Should it?','a-for','a-against',true,now())`)
  await q(`INSERT INTO debate_votes(id,"debateId","userId",side) VALUES ('v1','d1','u-reader','FOR')`)
  await q(`INSERT INTO debate_votes(id,"debateId","anonymousId",side) VALUES ('v2','d1','anon-1','AGAINST')`)
}

/** Everything that existed before, column by column, in a stable order. */
async function snapshot(c: Client) {
  const out: Record<string, unknown> = {}
  const tables: Record<string, string> = {
    users: 'SELECT id,email,name,role FROM users ORDER BY id',
    team_members: 'SELECT id,"userId",name,role,"publicTier",bio,image,email,"order","isActive" FROM team_members ORDER BY id',
    articles: 'SELECT id,title,slug,status,"deletedAt","isDebate" FROM articles ORDER BY id',
    debates: 'SELECT id,title,"forArticleId","againstArticleId","isActive","closesAt","createdAt","updatedAt" FROM debates ORDER BY id',
    debate_votes: 'SELECT id,"debateId","userId","anonymousId",side FROM debate_votes ORDER BY id',
  }
  for (const [name, query] of Object.entries(tables)) out[name] = (await c.query(query)).rows
  return out
}

const constraints = async (c: Client) =>
  (await c.query(`SELECT conrelid::regclass::text AS t, conname, pg_get_constraintdef(oid) AS def FROM pg_constraint
    WHERE conrelid::regclass::text IN ('team_members','debates','debate_votes','articles') ORDER BY 1,2`)).rows
const indexes = async (c: Client) =>
  (await c.query(`SELECT tablename, indexname, indexdef FROM pg_indexes WHERE schemaname='public' AND tablename IN ('team_members','debates','debate_votes','articles') ORDER BY 1,2`)).rows
const rls = async (c: Client) =>
  (await c.query(`SELECT relname, relrowsecurity FROM pg_class WHERE relname IN ('team_members','debates','debate_votes','articles') AND relkind='r' ORDER BY 1`)).rows
const policies = async (c: Client) => (await c.query(`SELECT tablename, policyname, roles, cmd FROM pg_policies WHERE tablename IN ('team_members','debates','debate_votes','articles') ORDER BY 1,2`)).rows
const apply = async (c: Client) => { for (const file of MINE) await c.query(file) }

describe('admin-overhaul migrations on the previous schema with real data', () => {
  it('preserve every existing row exactly, keep links, constraints, indexes and RLS, and are idempotent', async () =>
    withDatabase(async (c) => {
      await seed(c)
      const before = { data: await snapshot(c), constraints: await constraints(c), indexes: await indexes(c), rls: await rls(c), policies: await policies(c) }
      expect(before.rls.every((r) => r.relrowsecurity)).toBe(true)

      await apply(c)
      await apply(c) // a second run changes nothing and raises nothing

      // Existing data, byte for byte.
      expect(await snapshot(c)).toEqual(before.data)
      // Links are exactly as they were: the chief stays linked to the same account, legacy cards stay unlinked.
      const cards = (await c.query(`SELECT id,"userId",role,"order" FROM team_members ORDER BY id`)).rows
      expect(cards).toEqual([
        { id: 'c-chief', userId: 'u-chief', role: 'Editor-in-Chief', order: 1 },
        { id: 'c-hidden', userId: null, role: 'Writer', order: 90 },
        { id: 'c-legacy', userId: null, role: 'Senior Editor', order: 20 },
        { id: 'c-writer', userId: 'u-writer', role: 'Writer', order: 50 },
      ])

      // Nothing existing was dropped or altered: previous constraints and indexes are all still present, unchanged.
      const after = { constraints: await constraints(c), indexes: await indexes(c) }
      for (const old of before.constraints) expect(after.constraints, old.conname).toContainEqual(old)
      for (const old of before.indexes) expect(after.indexes, old.indexname).toContainEqual(old)
      // The only additions are the two documented indexes? One: the debates visibility index.
      const added = after.indexes.filter((i) => !before.indexes.some((o) => o.indexname === i.indexname)).map((i) => i.indexname)
      expect(added).toEqual(['debates_deletedAt_unpublishedAt_idx'])
      expect(after.constraints).toEqual(before.constraints) // no constraint added or removed

      // RLS posture identical: still enabled, same policies.
      expect(await rls(c)).toEqual(before.rls)
      expect(await policies(c)).toEqual(before.policies)

      // New columns: all existing debates are "published, not deleted"; every card got a real timestamp.
      expect((await c.query(`SELECT "unpublishedAt","deletedAt","deletedById" FROM debates`)).rows).toEqual([{ unpublishedAt: null, deletedAt: null, deletedById: null }])
      expect((await c.query(`SELECT count(*)::int AS n FROM team_members WHERE "updatedAt" IS NULL`)).rows[0].n).toBe(0)
      expect((await c.query(`SELECT is_nullable FROM information_schema.columns WHERE table_name='team_members' AND column_name='updatedAt'`)).rows[0].is_nullable).toBe('NO')

      // Public visibility is unchanged: the existing debate and its articles are still public.
      expect((await c.query(`SELECT count(*)::int AS n FROM debates WHERE "deletedAt" IS NULL AND "unpublishedAt" IS NULL`)).rows[0].n).toBe(1)
      expect((await c.query(`SELECT count(*)::int AS n FROM articles WHERE status='PUBLISHED'`)).rows[0].n).toBe(3)
      // The healing statement found nothing to do.
      expect((await c.query(`SELECT count(*)::int AS n FROM articles WHERE status='ARCHIVED'`)).rows[0].n).toBe(0)
    }))

  it('uniqueness still holds: one card per account, one membership per email', async () =>
    withDatabase(async (c) => {
      await seed(c)
      await apply(c)
      await expect(c.query(`INSERT INTO team_members(id,"userId",name,role) VALUES ('dup','u-chief','Second Chief','Writer')`)).rejects.toMatchObject({ code: '23505' })
      await expect(c.query(`INSERT INTO debate_votes(id,"debateId","userId",side) VALUES ('v3','d1','u-reader','AGAINST')`)).rejects.toMatchObject({ code: '23505' }) // one vote per user per debate
      // Orphans cannot appear: foreign keys still enforced.
      await expect(c.query(`INSERT INTO team_members(id,"userId",name,role) VALUES ('orphan','no-such-user','X','Writer')`)).rejects.toMatchObject({ code: '23503' })
      await expect(c.query(`INSERT INTO debates(id,title,"forArticleId","againstArticleId","updatedAt") VALUES ('d2','x','nope','a-against',now())`)).rejects.toMatchObject({ code: '23503' })
    }))

  it('the guard works for a role that bypasses nothing and cannot see debates through RLS (SECURITY DEFINER)', async () =>
    withDatabase(async (c) => {
      await seed(c)
      await apply(c)
      await c.query(`UPDATE debates SET "unpublishedAt" = now() WHERE id='d1'; UPDATE articles SET status='ARCHIVED' WHERE id IN ('a-for','a-against')`)
      const role = `consilium_app_${randomUUID().replaceAll('-', '')}`
      await c.query(`CREATE ROLE "${role}" NOLOGIN`)
      try {
        // The application role may write articles (via a policy) but has NO policy on debates: it sees none of them.
        await c.query(`GRANT USAGE ON SCHEMA public TO "${role}"; GRANT SELECT, UPDATE ON articles TO "${role}"; GRANT SELECT ON debates TO "${role}"`)
        await c.query(`CREATE POLICY probe_articles ON articles FOR ALL TO "${role}" USING (true) WITH CHECK (true)`)
        await c.query(`SET ROLE "${role}"`)
        expect((await c.query(`SELECT count(*)::int AS n FROM debates`)).rows[0].n).toBe(0) // blind to debates, as a non-owner under RLS
        // ...yet the guard still refuses, because it runs with its owner's rights.
        await expect(c.query(`UPDATE articles SET status='PUBLISHED' WHERE id='a-for'`)).rejects.toThrow(/HIDDEN_DEBATE_ARTICLE/)
        // An unrelated article is unaffected by the same role.
        await c.query(`UPDATE articles SET title = 'Plain edited' WHERE id='a-plain'`)
        await c.query('RESET ROLE')
        expect((await c.query(`SELECT status FROM articles WHERE id='a-for'`)).rows[0].status).toBe('ARCHIVED')
        // The new columns are not exposed to the public API roles.
        expect((await c.query(`SELECT has_column_privilege('anon','team_members','updatedAt','SELECT') AS a, has_column_privilege('anon','debates','deletedAt','SELECT') AS d`)).rows[0]).toEqual({ a: false, d: false })
        expect((await c.query(`SELECT has_column_privilege('authenticated','team_members','updatedAt','SELECT') AS a`)).rows[0].a).toBe(false)
        expect((await c.query(`SELECT has_function_privilege('anon','prevent_hidden_debate_article_publication()','EXECUTE') AS e`)).rows[0].e).toBe(true) // trigger functions cannot be called directly, so this grants nothing
      } finally {
        await c.query('RESET ROLE').catch(() => {})
        await c.query(`DROP POLICY IF EXISTS probe_articles ON articles; REVOKE ALL ON articles, debates FROM "${role}"; REVOKE USAGE ON SCHEMA public FROM "${role}"; DROP ROLE IF EXISTS "${role}"`)
      }
    }))

  it('the documented rollback returns the previous shape and no data changes; the migrations then reapply', async () =>
    withDatabase(async (c) => {
      await seed(c)
      const before = await snapshot(c)
      const shapeBefore = { constraints: await constraints(c), indexes: await indexes(c) }
      await apply(c)
      await c.query(ROLLBACK)
      expect(await snapshot(c)).toEqual(before)
      expect({ constraints: await constraints(c), indexes: await indexes(c) }).toEqual(shapeBefore)
      expect((await c.query(`SELECT column_name FROM information_schema.columns WHERE table_name='debates' AND column_name IN ('unpublishedAt','deletedAt','deletedById')`)).rowCount).toBe(0)
      expect((await c.query(`SELECT 1 FROM pg_trigger WHERE tgname='articles_hidden_debate_guard'`)).rowCount).toBe(0)
      await apply(c)
      expect(await snapshot(c)).toEqual(before)
    }))

  it('a database that already holds a publicly exposed hidden-debate article is healed by migration 3, and nothing else changes', async () =>
    withDatabase(async (c) => {
      await seed(c)
      await c.query(`${MINE[0]}`) // lifecycle columns only, as on a deployment that applied step 1 but not step 3
      await c.query(`UPDATE debates SET "unpublishedAt" = now() WHERE id='d1'`) // hidden, yet both articles still PUBLISHED
      expect((await c.query(`SELECT count(*)::int AS n FROM articles WHERE status='PUBLISHED'`)).rows[0].n).toBe(3)
      await c.query(MINE[1]); await c.query(MINE[2])
      expect((await c.query(`SELECT id,status FROM articles ORDER BY id`)).rows).toEqual([
        { id: 'a-against', status: 'ARCHIVED' }, { id: 'a-for', status: 'ARCHIVED' }, { id: 'a-plain', status: 'PUBLISHED' },
      ])
    }))
})
