-- Economics glossary seed: 86 starter terms with definitions, aliases and
-- verified learn-more links on reputable economics sources (Bank of England,
-- ECB, IMF, ONS, OBR, Federal Reserve, St. Louis Fed, SEC investor.gov,
-- House of Commons Library, Econlib, Britannica).
-- ALREADY APPLIED to the live Supabase database on 2026-06-11; kept here so
-- the dataset is version-controlled and can be replayed on a fresh environment.
--
-- "createdAt"/"updatedAt" are set explicitly in UTC: prisma db push creates
-- "updatedAt" with no database default (Prisma fills it client-side, always
-- UTC), and a bare CURRENT_TIMESTAMP would write session-local time, which
-- breaks newest-first ordering against Prisma-written rows.
-- Idempotent: ON CONFLICT (lower("term")) DO NOTHING means re-running it never
-- duplicates or overwrites terms; the arbiter is the case-insensitive
-- lower(term) unique index from 20260610_glossary_terms.sql, which must be
-- applied first.
-- Terms edited later in the admin UI keep their edits; this file is the seed,
-- not the source of truth.

INSERT INTO "glossary_terms" ("id", "term", "aliases", "definition", "learnMoreUrl", "isActive", "createdAt", "updatedAt")
VALUES
  ('c6y7afmoel77omdb7etktnxm1', 'inflation', '{}'::text[], 'The rate at which prices across the economy rise over time, reducing what each pound can buy. In the UK it is usually measured by the annual change in the Consumer Price Index, and the Bank of England targets 2%.', 'https://www.bankofengland.co.uk/explainers/what-is-inflation', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ccdram3xhktwwiv839y6sclf4', 'deflation', '{}'::text[], 'A sustained fall in the general level of prices, the opposite of inflation. It sounds like good news but can be damaging: shoppers delay purchases expecting cheaper prices later, and debts become harder to repay because money owed grows in real terms.', 'https://www.britannica.com/topic/deflation-economics', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('caw42v1ceqptxdr0wz5ae48hg', 'disinflation', '{}'::text[], 'A slowdown in the rate of inflation. Prices are still rising, but more slowly than before, for example inflation falling from 8% to 3%. It is different from deflation, where prices actually fall.', 'https://www.stlouisfed.org/open-vault/2023/august/explaining-inflation-disinflation-deflation', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c2k99pw6x8l68yvf1cl152mbt', 'stagflation', '{}'::text[], 'The unhappy combination of stagnant growth, high unemployment and high inflation at the same time. It is hard to treat: raising interest rates to fight inflation weakens growth further, while stimulus to boost growth fuels inflation.', 'https://www.britannica.com/topic/stagflation', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ceu73mbjv2y73f2u85ugtfudq', 'hyperinflation', '{}'::text[], 'Extremely rapid, out-of-control inflation, often defined as prices rising more than 50% a month. Money loses value so fast that people rush to spend it immediately. Weimar Germany in the 1920s and Zimbabwe in the 2000s are the classic examples.', 'https://www.econlib.org/library/Enc/Hyperinflation.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cdgd70mw8lblp52fgi2qe633n', 'gross domestic product', ARRAY['GDP']::text[], 'The total value of all goods and services produced in a country over a period, usually a quarter or a year. It is the standard yardstick for the size of an economy, and two consecutive quarters of falling GDP is a common rule of thumb for a recession.', 'https://www.bankofengland.co.uk/explainers/what-is-gdp', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cerga1llhepbjd4xv45eskxwr', 'recession', '{}'::text[], 'A period when an economy shrinks rather than grows. A widely used rule of thumb is two consecutive quarters of falling GDP. Recessions typically bring rising unemployment, falling investment and weaker tax receipts.', 'https://www.imf.org/external/pubs/ft/fandd/basics/recess.htm', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c67egxeg4d8r5ng08rrt94kmr', 'depression', ARRAY['economic depression']::text[], 'A severe and prolonged downturn, far deeper and longer than an ordinary recession. The defining example is the Great Depression of the 1930s, when output collapsed and unemployment stayed very high for years.', 'https://www.britannica.com/money/depression-economics', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cf11hacdmwbnmh2uex5cuu9ng', 'business cycle', ARRAY['economic cycle']::text[], 'The recurring rise and fall of economic activity over time: expansion, peak, contraction and recovery. No two cycles are identical, but economies rarely grow in a straight line.', 'https://www.econlib.org/library/Enc/BusinessCycles.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c1jaa6y9160d7mstj8xqdbzza', 'monetary policy', '{}'::text[], 'How a central bank manages the cost and availability of money to keep inflation stable and support the economy, mainly by setting interest rates and, at times, buying or selling assets. In the UK this is the job of the Bank of England.', 'https://www.bankofengland.co.uk/monetary-policy', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c9rlfm2ogrj45sout5t2pdgkd', 'fiscal policy', '{}'::text[], 'Government decisions about taxing and spending, used to influence the economy. Cutting taxes or raising spending can boost demand; the reverse cools it. Fiscal policy is set by the government, unlike monetary policy, which is set by the central bank.', 'https://www.britannica.com/money/fiscal-policy', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c3fbn4pmafepuuq4jvr7wacn5', 'quantitative easing', ARRAY['QE']::text[], 'A central bank policy of creating new money to buy assets, mainly government bonds, in order to push down longer-term interest rates and support the economy. Used heavily after the 2008 financial crisis and during the pandemic, when ordinary rate cuts had run out of room.', 'https://www.bankofengland.co.uk/monetary-policy/quantitative-easing', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c8cm7rc46jg6oxhz7ueps77kx', 'quantitative tightening', ARRAY['QT']::text[], 'The reverse of quantitative easing: the central bank shrinks its balance sheet by selling the bonds it bought or letting them mature without replacement. This withdraws money from the financial system and tends to nudge longer-term interest rates up.', 'https://www.bankofengland.co.uk/monetary-policy/quantitative-easing', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cel64z7ywqudj83a0xgdfwcq3', 'Bank Rate', ARRAY['base rate']::text[], 'The official interest rate set by the Bank of England''s Monetary Policy Committee. It determines what the Bank pays commercial banks on their reserves and anchors the rates households and businesses pay on mortgages, loans and savings.', 'https://www.bankofengland.co.uk/monetary-policy/the-interest-rate-bank-rate', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c6dw6f86cq3wmue21gdoru95a', 'interest rate', ARRAY['interest rates']::text[], 'The price of borrowing money, or the reward for saving it, expressed as a percentage per year. Higher rates make loans dearer and saving more attractive, cooling spending; lower rates do the opposite.', 'https://www.bankofengland.co.uk/explainers/what-are-interest-rates', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cpagjnxwlet8q5bxc1kgpa9zs', 'central bank', '{}'::text[], 'The public institution that issues a country''s currency, sets official interest rates, and acts as banker to the government and commercial banks. The Bank of England, the US Federal Reserve and the European Central Bank are the best-known examples.', 'https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me/html/what-is-a-central-bank.en.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ceqapji221x37fxj15uldr4er', 'consumer price index', ARRAY['CPI']::text[], 'A measure of the average price of a representative basket of goods and services bought by households. The annual change in the CPI is the most widely quoted measure of inflation in the UK, compiled by the Office for National Statistics.', 'https://www.ons.gov.uk/economy/inflationandpriceindices', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cdttc9zbawbyofkfrjk80v6pf', 'unemployment rate', '{}'::text[], 'The share of the labour force that is out of work but actively looking for a job. It misses people who have given up searching or who want more hours, so economists often look at it alongside other labour market measures.', 'https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5ghv769frtwqa9unjbd6agl3', 'Phillips curve', '{}'::text[], 'The observed trade-off between unemployment and inflation: when unemployment is low, wages and prices tend to rise faster. The relationship has weakened and shifted over the decades, but it still shapes how central banks think about the labour market.', 'https://www.econlib.org/library/Enc/PhillipsCurve.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cp8ebav4xyzarl38915mbc718', 'opportunity cost', '{}'::text[], 'The value of the best alternative you give up when you make a choice. An evening spent studying costs you the film you did not watch; a government pound spent on defence is a pound not spent on schools. It is the core idea behind ''there is no free lunch''.', 'https://www.econlib.org/library/Enc/OpportunityCost.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cawcey24stlx8a0q2xxvdwl5g', 'comparative advantage', '{}'::text[], 'The idea that countries gain from trade by specialising in what they produce at the lowest opportunity cost, even if one country is better at producing everything. It is the classic argument for free trade, first set out by David Ricardo in 1817.', 'https://www.econlib.org/library/Enc/ComparativeAdvantage.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ce1hy7vjhcp7bqv72y6u2reo5', 'elasticity', ARRAY['price elasticity']::text[], 'A measure of how strongly buyers or sellers respond to a change, most often how much demand falls when the price rises. Demand for essentials like fuel is inelastic (people keep buying); demand for luxuries tends to be elastic.', 'https://www.britannica.com/money/elasticity-economics', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c2y7nti0ah4fkfgg19n7y5blo', 'supply and demand', '{}'::text[], 'The two forces that set prices in a market economy. When demand outstrips supply, prices rise; when supply exceeds demand, prices fall. The price at which the two balance is called the equilibrium price.', 'https://www.britannica.com/money/supply-and-demand', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cdw5pu2gd3191jo7krl8yeovn', 'balance of trade', ARRAY['trade balance', 'trade deficit', 'trade surplus']::text[], 'The difference between the value of a country''s exports and its imports of goods and services. Exporting more than you import gives a trade surplus; importing more gives a trade deficit.', 'https://www.britannica.com/money/balance-of-trade', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ccsk3y1qzrx43474tpivbvnp6', 'current account', '{}'::text[], 'The broadest regular measure of a country''s transactions with the rest of the world, covering trade in goods and services plus cross-border income and transfers. A persistent deficit means a country is borrowing from, or selling assets to, the rest of the world.', 'https://www.imf.org/en/publications/fandd/issues/series/back-to-basics/current-account-deficits', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5tdf06p9zg5ucxh8rispxd9n', 'exchange rate', '{}'::text[], 'The price of one currency in terms of another, such as how many dollars one pound buys. A weaker pound makes imports dearer and exports cheaper; a stronger pound does the reverse.', 'https://www.britannica.com/money/exchange-rate', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c24ii9vo4rle7njhkpfbzyot2', 'devaluation', '{}'::text[], 'A deliberate reduction in the value of a currency by the government or central bank under a fixed exchange rate system. When a floating currency simply falls in the market, the more precise term is depreciation.', 'https://www.britannica.com/money/devaluation', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cefciw14w4z9wrxwpickycez0', 'tariff', ARRAY['tariffs']::text[], 'A tax charged on goods as they cross a border, usually on imports. Tariffs raise revenue and shield domestic producers from foreign competition, but they also raise prices for consumers and invite retaliation.', 'https://www.britannica.com/money/tariff', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c426wxjwbqmjveywpua7yjut2', 'budget deficit', ARRAY['fiscal deficit']::text[], 'The gap when a government spends more in a year than it raises in taxes and other revenue, covered by borrowing. The opposite, rarer, case is a budget surplus. The accumulated total of past deficits is the national debt.', 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cf1b6eluos1mgsm42zxda6x43', 'national debt', ARRAY['public debt', 'government debt']::text[], 'The total stock of money a government owes from past borrowing, usually compared with the size of the economy as a ratio to GDP. In the UK it is mostly owed in the form of gilts. It is the running total of past deficits, not one year’s borrowing.', 'https://www.econlib.org/library/Enc/GovernmentDebtandDeficits.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cdvg68n9xeebr1gyjze8ah91x', 'bond', ARRAY['bonds']::text[], 'An IOU issued by a government or company to borrow money. The buyer hands over cash now in exchange for regular interest payments (the coupon) and repayment of the face value at a set date. Bond prices move in the opposite direction to their yields.', 'https://www.britannica.com/money/bond-finance', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c2sfaqlof72ih7r157wqoxms2', 'gilt', ARRAY['gilts']::text[], 'A bond issued by the UK government, so called because the original certificates had gilded edges. Gilts are how the British state borrows, and the gilt market sets the benchmark for many other UK interest rates.', 'https://commonslibrary.parliament.uk/what-are-gilts-a-simple-guide/', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cdgpjn4cavlfs3cakpgflwdr7', 'yield', '{}'::text[], 'The annual return an investor earns on a bond or other asset, expressed as a percentage of its current price. When a bond''s price falls its yield rises, and vice versa, which is why headlines about ''rising yields'' mean bond prices are dropping.', 'https://www.investor.gov/introduction-investing/investing-basics/glossary/yield', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c6qglf269maaq943o29azvl9e', 'yield curve', '{}'::text[], 'A chart of government bond yields from short maturities to long ones. It normally slopes upward, since lenders demand more for locking money away longer. When short-term yields rise above long-term ones (an inverted curve), markets are often pricing in a recession.', 'https://www.investor.gov/introduction-investing/investing-basics/glossary/yield-curve', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c2ihcsk69b4m9zbzbv0gpjqgm', 'liquidity', '{}'::text[], 'How quickly and cheaply an asset can be turned into cash without moving its price. Cash is perfectly liquid; a house is not. The word is also used for the overall ease of trading in a market, which can evaporate in a crisis.', 'https://www.investor.gov/introduction-investing/investing-basics/glossary/liquidity-or-marketability', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c7aiczrh57vqwk3c9qfqcwrwb', 'leverage', ARRAY['gearing']::text[], 'Using borrowed money to make an investment bigger than your own capital would allow. It magnifies gains when prices move your way and magnifies losses when they do not, which is why excessive leverage is at the heart of most financial crises.', 'https://www.britannica.com/money/what-is-financial-leverage-trading', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c4qxo238cnmug5lr3r0k04a68', 'collateral', '{}'::text[], 'An asset a borrower pledges to a lender, which the lender can seize if the loan is not repaid. A house is the collateral for a mortgage. Good collateral lets borrowers get larger loans at lower rates.', 'https://www.britannica.com/money/collateral-finance', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ccudaxkge8kvvytfecka91ej4', 'credit crunch', '{}'::text[], 'A sudden squeeze in lending, when banks sharply tighten the terms on which they will lend or stop lending altogether, regardless of borrowers'' quality. The phrase became a household term in the 2007-08 financial crisis.', 'https://www.britannica.com/money/financial-crisis-of-2007-2008', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5xunk9tkv4qxiae8bs3x95f8', 'moral hazard', '{}'::text[], 'The tendency to take more risk when someone else bears the cost. A driver with full insurance may drive less carefully; a bank that expects a government rescue may lend more recklessly. It is a central dilemma in designing bailouts and insurance.', 'https://www.britannica.com/money/moral-hazard', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c488xrkcqsg4cib5jvrplw709', 'adverse selection', '{}'::text[], 'When the people most eager to take a deal are precisely the ones the other side least wants, because each side knows something the other does not. Health insurance attracts the least healthy customers; used-car markets attract sellers of hidden lemons.', 'https://www.britannica.com/money/adverse-selection', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c8dhzfvlktqqtkaqtw7jodv40', 'asymmetric information', ARRAY['information asymmetry']::text[], 'A situation where one side of a deal knows more than the other, such as a seller who knows a car''s faults or a borrower who knows their own finances. It underlies problems like adverse selection and moral hazard, and explains rules forcing disclosure.', 'https://www.econlib.org/library/Enc/Information.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cek07c3ft279zs1kmvqazmvau', 'externality', ARRAY['externalities']::text[], 'A cost or benefit from an activity that lands on people who had no say in it. Pollution is a negative externality; a neighbour''s vaccination is a positive one. Markets overproduce the former and underproduce the latter, a classic case for taxes and subsidies.', 'https://www.econlib.org/library/Enc/Externalities.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c3wnf7mp9twnna6vrtiqm64oy', 'public good', ARRAY['public goods']::text[], 'Something one person''s use does not diminish and from which non-payers cannot be excluded, like street lighting, clean air or national defence. Because private firms struggle to charge for them, public goods are usually funded by government.', 'https://www.econlib.org/library/Enc/PublicGoods.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c1qxe44g8lvycicnweskqhukc', 'monopoly', '{}'::text[], 'A market with a single seller and no close substitutes, giving that seller the power to set prices well above costs. Monopolies can arise from scale, patents, or control of a key resource, and are the main target of competition policy.', 'https://www.econlib.org/library/Enc/Monopoly.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c3brzjfl4cdwf8fhof7sn4b39', 'oligopoly', '{}'::text[], 'A market dominated by a handful of large firms, such as UK supermarkets or mobile networks. Each firm''s choices visibly affect the others, so strategy, price wars and tacit cooperation matter in ways they do not in more crowded markets.', 'https://www.britannica.com/money/oligopoly', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ceo7e15wb2krgg9cjxit5przf', 'monopsony', '{}'::text[], 'A market with effectively one buyer rather than one seller, giving the buyer power to push prices, or wages, down. A single dominant employer in a small town has monopsony power over local workers.', 'https://www.britannica.com/money/monopsony', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5kjymyi5h7m0pmceb6bz61xc', 'market failure', '{}'::text[], 'Any situation where free markets, left alone, deliver a wasteful or harmful outcome: pollution, under-provided public goods, monopoly pricing, or deals undermined by one side knowing more than the other. It is the standard economic case for government intervention.', 'https://www.britannica.com/money/market-failure', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c9a5upisi5028r8v75fkso7qh', 'purchasing power parity', ARRAY['PPP']::text[], 'A way of comparing countries'' incomes and prices by asking what money actually buys in each place, rather than using market exchange rates. The Big Mac index is a playful version: if a burger is cheaper in one country, its currency may be undervalued.', 'https://www.britannica.com/money/purchasing-power-parity', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c2z2rfgwizuvj1kxf3ggrgcf6', 'productivity', '{}'::text[], 'How much output is produced per worker, or per hour worked. It is the main driver of living standards over the long run; weak productivity growth has been the central puzzle of the UK economy since the 2008 crisis.', 'https://www.ons.gov.uk/economy/economicoutputandproductivity', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c2775yssc0ux2uyr8f6a7rizx', 'human capital', '{}'::text[], 'The skills, knowledge, health and experience embodied in people, built up through education, training and practice. Economists treat it as a form of capital because investing in it raises a person''s, and a nation''s, future earning power.', 'https://www.econlib.org/library/Enc/HumanCapital.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c3bsvqs3dchlpxd18z6d7890i', 'austerity', '{}'::text[], 'A policy of cutting government spending or raising taxes to shrink the budget deficit. Supporters argue it keeps debt sustainable; critics argue that cutting too hard in a weak economy deepens the downturn. The word defined UK fiscal policy in the 2010s.', 'https://www.britannica.com/money/austerity', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c913q1oabhcpfoahjznq2yazn', 'multiplier effect', ARRAY['fiscal multiplier']::text[], 'The idea that an initial injection of spending creates income that is partly re-spent, generating further rounds of income. If the government builds a railway, workers spend their wages in shops, whose staff spend in turn, so output can rise by more than the original outlay.', 'https://www.stlouisfed.org/open-vault/2020/february/meet-multiplier-effect', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ce2cz2u8trms9ndzingn1td5y', 'crowding out', ARRAY['crowding out effect']::text[], 'The argument that government borrowing and spending can displace private activity, for instance by pushing up interest rates and making business investment more expensive. How much crowding out actually happens, especially in a slump, is a long-running dispute.', 'https://www.britannica.com/money/government-budget/Economics-of-government-borrowing', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c4py6l9ac4fqzyfnwxe2corjk', 'liquidity trap', '{}'::text[], 'A situation where interest rates are already near zero and further cuts cannot stimulate the economy, because people and banks prefer to sit on cash. It is the scenario that pushed central banks toward unconventional tools like quantitative easing.', 'https://www.stlouisfed.org/publications/regional-economist/april-2014/the-liquidity-trap-an-alternative-explanation-for-todays-low-inflation', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c9d881kwz33t9uwt1aq3he4mw', 'money supply', '{}'::text[], 'The total amount of money circulating in an economy, from notes and coins to bank deposits. Statisticians track it in tiers, from narrow measures like M0 to broad ones like M4 in the UK. Monetarists argue its growth rate ultimately drives inflation.', 'https://www.federalreserve.gov/faqs/money_12845.htm', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c9s0bux0hgq80tvropwrmwa4c', 'lender of last resort', '{}'::text[], 'The central bank''s role as emergency lender to banks that are solvent but cannot raise cash quickly enough to meet withdrawals. By standing ready to lend against good collateral, it can stop a panic from toppling otherwise healthy institutions.', 'https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me-more/html/what-is-a-lender-of-last-resort.en.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c31z6o5fucuteqnzy3w7enneu', 'bank run', '{}'::text[], 'A rush of depositors trying to withdraw their money at once, driven by fear the bank may fail. Because banks lend out most deposits rather than keeping them in the vault, even a healthy bank can collapse if everyone demands cash at the same time. Northern Rock in 2007 was Britain’s most famous modern run.', 'https://www.econlib.org/library/Enc/BankRuns.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('caltg0fdkpox4btqois79319a', 'securitisation', ARRAY['securitization']::text[], 'The practice of bundling loans, such as mortgages, into packages that are sold to investors as tradable securities. It spreads risk and frees banks to lend more, but opaque securitised mortgages were at the core of the 2008 financial crisis.', 'https://www.britannica.com/money/securitization', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c30mw3cjb20ellr8zg907g5jg', 'derivative', ARRAY['derivatives']::text[], 'A financial contract whose value derives from something else: a share price, an interest rate, an exchange rate or a commodity. Futures, options and swaps are the main families. Derivatives are used both to reduce risk (hedging) and to take it (speculation).', 'https://www.investor.gov/introduction-investing/investing-basics/glossary/derivatives', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cb9ulgqc5by4nx1va8othk7wb', 'hedging', '{}'::text[], 'Taking a position that offsets a risk you already have, like an airline locking in fuel prices or an exporter fixing an exchange rate in advance. Hedging sacrifices some potential upside in exchange for certainty.', 'https://www.britannica.com/money/hedging', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cj6lf0opoh9trt4h6ytt41077', 'arbitrage', '{}'::text[], 'Buying something in one market and simultaneously selling it in another to profit from a price difference, in principle without risk. Arbitrageurs'' activity tends to erase the very gaps they exploit, keeping prices consistent across markets.', 'https://www.britannica.com/money/arbitrage-finance', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c1tm8w6e2ierh2bfm3y8fo596', 'bull market', '{}'::text[], 'A sustained period of rising prices and optimism in a market, most often said of shares. A common rule of thumb is a rise of 20% or more from a recent low.', 'https://www.britannica.com/money/bull-market', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cc34p7kqs7lx8xpfmebs0251x', 'bear market', '{}'::text[], 'A sustained period of falling prices and pessimism, conventionally a drop of 20% or more from a recent peak. The name reputedly comes from the way a bear swipes downward.', 'https://www.britannica.com/money/bear-market-trading', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cf164jw97j9sebcbroz0v2tqz', 'volatility', '{}'::text[], 'How much and how fast a price swings around. Volatile assets offer bigger potential gains and losses; measures of expected volatility, like the VIX index, are often read as a gauge of market fear.', 'https://www.britannica.com/money/volatility', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cbvf19ysst7p26iw10knnmazu', 'aggregate demand', '{}'::text[], 'The total spending on an economy''s goods and services at a given time: household consumption, business investment, government spending and net exports. When aggregate demand outruns what the economy can supply, inflation tends to rise.', 'https://www.britannica.com/topic/aggregate-demand', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5egkh6f6ouucy6xraht6gq3h', 'aggregate supply', '{}'::text[], 'The total amount of goods and services an economy can produce at a given price level, ultimately limited by its workers, capital and technology. Shocks to supply, like an oil price spike, can raise inflation and weaken growth at the same time.', 'https://www.econlib.org/library/Topics/College/aggregatesupply.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cbggwc4kvo9u07gpkhfmv2jx7', 'marginal utility', '{}'::text[], 'The extra satisfaction you get from one more unit of something. It usually diminishes: the first slice of pizza is bliss, the fifth is a chore. The idea underpins downward-sloping demand curves and much of modern price theory.', 'https://www.britannica.com/money/marginal-utility', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5dq4ybbabgy31vk6tm908jke', 'economies of scale', '{}'::text[], 'Cost advantages that come with size: spreading fixed costs over more units, buying inputs in bulk, specialising workers and machines. They explain why some industries are dominated by a few giant producers.', 'https://www.britannica.com/money/economy-of-scale', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('ca3zs13e4alilzorf8ffxqqkr', 'creative destruction', '{}'::text[], 'Joseph Schumpeter''s name for the way innovation kills old industries as it builds new ones, as the car did to coaching inns and streaming did to video shops. The churn is painful for incumbents and workers, but it is the engine of long-run growth.', 'https://www.econlib.org/library/Enc/CreativeDestruction.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c325tq17fvouq6ntupy9olvj8', 'invisible hand', '{}'::text[], 'Adam Smith''s metaphor for how individuals pursuing their own interest in competitive markets can end up serving society''s, as if guided by an invisible hand. It is shorthand for the coordinating power of prices, not a claim that markets always get it right.', 'https://www.britannica.com/money/invisible-hand', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c25knxboxckh6p66gj9z6i82s', 'Keynesian economics', ARRAY['Keynesianism']::text[], 'The school of thought, after John Maynard Keynes, holding that economies can get stuck with high unemployment because total demand is too weak, and that government spending and tax cuts should fill the gap in downturns. It dominated post-war policy and returned to fashion after 2008.', 'https://www.econlib.org/library/Enc/KeynesianEconomics.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cf0fhlah7dzw4bxxpv6vx7s81', 'monetarism', '{}'::text[], 'The school of thought, associated with Milton Friedman, that inflation is ''always and everywhere a monetary phenomenon'' driven by the growth of the money supply. Its influence peaked around 1980, and it shaped central banks'' focus on controlling inflation.', 'https://www.econlib.org/library/Enc/Monetarism.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c79t4f2jmnk576kxxym6qkrbq', 'behavioural economics', ARRAY['behavioral economics']::text[], 'The field that studies how real people actually decide, with limited willpower, short attention and predictable biases, rather than as perfectly rational calculators. Its findings, like loss aversion and the power of defaults, are widely used in policy ''nudges''.', 'https://www.econlib.org/library/Enc/BehavioralEconomics.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c8uakb49apttp0uvbkox6r5zm', 'game theory', '{}'::text[], 'The study of strategic decisions, where the best choice depends on what others choose. It is used to analyse everything from price wars and auctions to wage bargaining and climate negotiations.', 'https://www.econlib.org/library/Enc/GameTheory.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c4wjbogxhmfc1nw2wvo0ersej', 'Nash equilibrium', '{}'::text[], 'A situation in a strategic game where no player can do better by changing their choice alone, given what everyone else is doing. Named after mathematician John Nash, it is game theory’s central idea of a stable outcome, even when that outcome is bad for everyone.', 'https://www.britannica.com/science/Nash-equilibrium', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c9ltp836sbtsb464hs7c7f8uq', 'Gini coefficient', ARRAY['Gini index']::text[], 'The most common single-number measure of inequality, running from 0 (everyone has the same income) to 1 (one person has everything). The UK''s income Gini is around 0.35, higher than most of western Europe but lower than the United States.', 'https://www.britannica.com/topic/Gini-Coefficient', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c87okox72mma423v0z662c7ni', 'progressive tax', ARRAY['progressive taxation']::text[], 'A tax that takes a larger percentage of income from higher earners than from lower ones, like UK income tax with its rising bands. The opposite is a regressive tax.', 'https://www.britannica.com/money/progressive-tax', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cbff8xlccimdygau00wqxfgw0', 'regressive tax', ARRAY['regressive taxation']::text[], 'A tax that takes a larger share of income from poorer households than richer ones. Flat-rate duties on fuel, alcohol and tobacco are regressive, because the same charge weighs more heavily on a small income.', 'https://www.britannica.com/money/regressive-tax', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c9dckv7nbodcny576pq67p99v', 'subsidy', ARRAY['subsidies']::text[], 'A government payment or tax break that lowers the cost of producing or buying something, such as renewable energy support or childcare funding. Subsidies can fix market failures or protect favoured industries, and they often outlive their original purpose.', 'https://www.britannica.com/money/subsidy', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c3fb40x6bp8myati9ygmipgvi', 'price ceiling', ARRAY['price cap']::text[], 'A legal maximum price for a good or service, such as a rent cap or an energy price cap. If set below the market price it helps those who can still buy, but tends to create shortages, queues and black markets.', 'https://www.econlib.org/library/Enc/PriceControls.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c5ztqu6jtl8do57p6z2uoshb8', 'rent seeking', ARRAY['rent-seeking']::text[], 'Trying to get richer by capturing existing wealth rather than creating new value, through lobbying for favourable rules, monopoly rights or subsidies. The ''rent'' is economist-speak for unearned gain, not the payment to a landlord.', 'https://www.econlib.org/library/Enc/RentSeeking.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cdmkvnpayl4jy5wzqhhes1yu2', 'sunk cost', ARRAY['sunk costs', 'sunk cost fallacy']::text[], 'Money already spent that cannot be recovered. Rationally it should be ignored in decisions about the future, but people routinely ''throw good money after bad'' to justify what they have spent. That mistake is the sunk cost fallacy.', 'https://www.britannica.com/money/sunk-cost', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('c8v70c4ag5khrby7kt6hut12m', 'real interest rate', '{}'::text[], 'An interest rate after stripping out inflation: roughly the quoted (nominal) rate minus the inflation rate. It is the truer price of borrowing; a 5% savings rate is a losing deal when inflation is 7%.', 'https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me/html/nominal_and_real_interest_rates.en.html', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('caob53uoi7r3hayfskfg07svm', 'basis point', ARRAY['basis points']::text[], 'One hundredth of a percentage point. Financial markets quote changes in interest rates and yields in basis points to avoid ambiguity: a rise from 4.00% to 4.25% is 25 basis points.', 'https://www.investor.gov/introduction-investing/investing-basics/glossary/basis-point', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cbomnk641vwjcx7h30yg7bt63', 'fractional reserve banking', '{}'::text[], 'The system in which banks keep only a fraction of deposits on hand and lend out the rest. It is how banks create credit and grow the economy, and also why they are vulnerable to runs if too many depositors want their cash at once.', 'https://www.bankofengland.co.uk/quarterly-bulletin/2014/q1/money-creation-in-the-modern-economy', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')),
  ('cayeprztk36dmt3fxvbjl4sjt', 'velocity of money', '{}'::text[], 'How many times a typical unit of money changes hands in a year. When velocity falls, as it did after 2008, even a big increase in the money supply may not produce inflation.', 'https://fred.stlouisfed.org/series/M2V', true, (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc'))
-- Arbiter is the case-insensitive term identity (the glossary_terms_term_lower_key
-- unique index): a row is skipped when its NAME is already taken, even if that
-- term was created in the admin UI under a different id. Targeting (id) instead
-- would make such re-runs fail with a unique violation on term. The inference
-- form is required here — ON CONSTRAINT cannot name an expression index.
ON CONFLICT (lower("term")) DO NOTHING;
